"""
Go Source File Classifier

Classifies Go source file paths into categories:
- RUNTIME_CORE: Core runtime (runtime/*)
- RUNTIME_INTERNAL: Runtime-critical internal packages
- STDLIB_INTERNAL: Standard library internal packages
- STDLIB_PUBLIC: Public standard library packages
- THIRD_PARTY: Third-party dependencies
- APPLICATION: User application code
- AUTOGENERATED: Compiler-generated code
- UNKNOWN: Unclassifiable

Handles:
- Relative paths (runtime/proc.go)
- Absolute paths (/home/user/go/src/runtime/proc.go)
- GOPATH paths (/home/user/go/pkg/mod/github.com/...)
- Vendor directories
- Module paths with versions (@v1.2.3)
"""

import re
from typing import Dict, Optional, Tuple
from enum import Enum


class FileCategory(Enum):
    """File classification categories."""
    RUNTIME_CORE = "runtime_core"
    RUNTIME_INTERNAL = "runtime_internal"
    STDLIB_INTERNAL = "stdlib_internal"
    STDLIB_PUBLIC = "stdlib_public"
    THIRD_PARTY = "third_party"
    APPLICATION = "application"
    AUTOGENERATED = "autogenerated"
    CGO = "cgo"
    UNKNOWN = "unknown"


# =============================================================================
# COMPLETE STDLIB TOP-LEVEL PACKAGES (Go 1.4 - 1.25+)
# These are the first path segments that indicate stdlib
# =============================================================================
STDLIB_TOP_LEVEL = frozenset({
    # Core packages
    'archive',
    'bufio',
    'builtin',
    'bytes',
    'cmp',          # Go 1.21+
    'compress',
    'container',
    'context',
    'crypto',
    'database',
    'debug',
    'embed',        # Go 1.16+
    'encoding',
    'errors',
    'expvar',
    'flag',
    'fmt',
    'go',
    'hash',
    'html',
    'image',
    'index',
    'io',
    'iter',         # Go 1.23+
    'log',
    'maps',         # Go 1.21+
    'math',
    'mime',
    'net',
    'os',
    'path',
    'plugin',
    'reflect',
    'regexp',
    'runtime',
    'slices',       # Go 1.21+
    'sort',
    'strconv',
    'strings',
    'structs',      # Go 1.24+
    'sync',
    'syscall',
    'testing',
    'text',
    'time',
    'unicode',
    'unique',       # Go 1.23+
    'unsafe',
    'weak',         # Go 1.24+
})

# =============================================================================
# INTERNAL PACKAGE PREFIXES
# =============================================================================

# Runtime-critical internal packages (low-level, used directly by runtime)
RUNTIME_INTERNAL_PREFIXES = frozenset({
    'internal/abi',
    'internal/bytealg',
    'internal/byteorder',
    'internal/chacha8rand',
    'internal/coverage/rtcov',
    'internal/cpu',
    'internal/goarch',
    'internal/godebugs',
    'internal/goexperiment',
    'internal/goos',
    'internal/msan',
    'internal/asan',
    'internal/race',
    'internal/runtime/atomic',
    'internal/runtime/exithook',
    'internal/runtime/maps',
    'internal/runtime/math',
    'internal/runtime/sys',
    'internal/runtime/syscall',
    'internal/runtime/cgroup',
    'internal/runtime/strconv',
    'internal/stringslite',
    'internal/sync',
})

# Stdlib internal packages (used by stdlib, not runtime-critical)
STDLIB_INTERNAL_PREFIXES = frozenset({
    'internal/bisect',
    'internal/buildcfg',
    'internal/cfg',
    'internal/coverage',
    'internal/diff',
    'internal/envvars',
    'internal/execabs',
    'internal/filepathlite',
    'internal/fmtsort',
    'internal/fuzz',
    'internal/godebug',
    'internal/goroot',
    'internal/gover',
    'internal/goversion',
    'internal/intern',
    'internal/itoa',
    'internal/lazyregexp',
    'internal/lazytemplate',
    'internal/nettrace',
    'internal/obscuretestdata',
    'internal/oserror',
    'internal/pkgbits',
    'internal/platform',
    'internal/poll',
    'internal/profile',
    'internal/profilerecord',
    'internal/reflectlite',
    'internal/safefilepath',
    'internal/saferio',
    'internal/singleflight',
    'internal/syscall',
    'internal/sysinfo',
    'internal/syslist',
    'internal/testenv',
    'internal/testlog',
    'internal/testpty',
    'internal/trace',
    'internal/txtar',
    'internal/types',
    'internal/unsafeheader',
    'internal/xcoff',
    'internal/zstd',
    # Crypto internal
    'crypto/internal',
    # Net internal  
    'net/internal',
    # Vendor internal (stdlib vendored deps)
    'vendor/golang.org',
})

# =============================================================================
# KNOWN THIRD-PARTY DOMAIN PATTERNS
# =============================================================================

# Exact domain matches (most common hosting platforms)
KNOWN_THIRD_PARTY_DOMAINS = frozenset({
    # Major Git hosting
    'github.com',
    'gitlab.com',
    'bitbucket.org',
    'gitee.com',
    'gitea.com',
    'codeberg.org',
    'sr.ht',
    'git.sr.ht',
    'sourcehut.org',
    
    # Go ecosystem
    'golang.org',
    'go.uber.org',
    'go.etcd.io',
    'go.mongodb.org',
    'go.opencensus.io',
    'go.opentelemetry.io',
    'go.step.sm',
    'go.einride.tech',
    
    # Google
    'google.golang.org',
    'cloud.google.com',
    'firebase.google.com',
    
    # Kubernetes ecosystem
    'k8s.io',
    'sigs.k8s.io',
    'helm.sh',
    'istio.io',
    'knative.dev',
    'oras.land',
    
    # Other major vendors
    'gopkg.in',
    'gonum.org',
    'gocloud.dev',
    'modernc.org',
    
    # Personal domains commonly used
    'honnef.co',
    'mvdan.cc',
    'rsc.io',
    'lukechampine.com',
    'nhooyr.io',
    'filippo.io',
    'zombiezen.com',
    'layeh.com',
    '4d63.com',
    'dmitri.shuralyov.com',
    'go4.org',
    'bazil.org',
    'mellium.im',
    'moul.io',
    'olympos.io',
    'periph.io',
    'toolman.org',
})

# TLDs commonly used for Go modules
GO_MODULE_TLDS = frozenset({
    'com', 'org', 'io', 'dev', 'net', 'co', 'sh', 'cc', 
    'me', 'land', 'tech', 'im', 'fm', 'ly', 'run', 'app',
})


def _normalize_filepath(filepath: str) -> str:
    """
    Normalize a Go source file path by stripping absolute path prefixes.
    
    Handles:
    - /home/user/go/src/runtime/proc.go -> runtime/proc.go
    - /usr/local/go/src/net/http/server.go -> net/http/server.go
    - /home/user/go/pkg/mod/github.com/foo/bar@v1.0.0/baz.go -> github.com/foo/bar/baz.go
    - C:\\Users\\user\\go\\src\\runtime\\proc.go -> runtime/proc.go
    
    Args:
        filepath: Raw file path from pclntab
        
    Returns:
        Normalized relative path
    """
    if not filepath:
        return filepath
    
    # Normalize slashes
    filepath = filepath.replace('\\', '/')
    
    # Strip leading slashes
    filepath = filepath.lstrip('/')
    
    # Pattern 1: Go SDK source path
    # Matches: anything/go/src/package/...
    # Also matches: anything/go1.XX/src/package/...
    # Also matches: anything/sdk/go1.XX/src/package/...
    sdk_patterns = [
        r'^.*/go\d*\.?\d*\.?\d*/src/(.+)$',  # go1.21.5/src/...
        r'^.*/sdk/go\d+\.\d+\.?\d*/src/(.+)$',  # sdk/go1.21/src/...
        r'^.*/go/src/(.+)$',  # go/src/...
        r'^.+/src/((?:runtime|internal|syscall|reflect|sync|crypto|net|os|io|fmt|errors|context|time|strings|bytes|bufio|strconv|unicode|sort|container|encoding|compress|archive|debug|go|hash|html|image|index|log|math|mime|path|plugin|regexp|testing|text|embed|maps|slices|cmp|iter|unique|weak|structs|database|expvar|flag)/.+)$',
    ]
    
    for pattern in sdk_patterns:
        match = re.match(pattern, filepath, re.IGNORECASE)
        if match:
            return match.group(1)
    
    # Pattern 2: GOPATH/pkg/mod (module cache)
    # Matches: anything/go/pkg/mod/github.com/user/repo@v1.2.3/file.go
    mod_match = re.match(r'^.*/go/pkg/mod/(.+)$', filepath, re.IGNORECASE)
    if mod_match:
        mod_path = mod_match.group(1)
        # Remove version suffix: github.com/foo/bar@v1.0.0/... -> github.com/foo/bar/...
        mod_path = re.sub(r'@v[^/]+/', '/', mod_path)
        # Handle !uppercase encoding in module paths
        # e.g., !azure -> Azure
        mod_path = re.sub(r'!([a-z])', lambda m: m.group(1).upper(), mod_path)
        return mod_path
    
    # Pattern 3: GOPATH/src (pre-modules)
    # Matches: anything/gopath/src/github.com/...
    gopath_match = re.match(r'^.*/(?:gopath|GOPATH)/src/(.+)$', filepath, re.IGNORECASE)
    if gopath_match:
        return gopath_match.group(1)
    
    # Pattern 4: Bazel-style paths
    # Matches: bazel-out/k8-fastbuild/bin/external/com_github_foo_bar/...
    bazel_match = re.match(r'^.*bazel[^/]*/[^/]+/bin/(?:external/)?(.+)$', filepath, re.IGNORECASE)
    if bazel_match:
        bazel_path = bazel_match.group(1)
        # Convert com_github_foo_bar to github.com/foo/bar
        bazel_path = re.sub(r'^com_github_([^/]+)_([^/]+)', r'github.com/\1/\2', bazel_path)
        bazel_path = re.sub(r'^org_golang_', 'golang.org/', bazel_path)
        bazel_path = re.sub(r'^io_k8s_', 'k8s.io/', bazel_path)
        return bazel_path
    
    # Pattern 5: _gomod_ prefix (Go module builds)
    if filepath.startswith('_gomod_/'):
        return filepath[8:]
    
    # Pattern 6: command-line-arguments (main package)
    if filepath.startswith('command-line-arguments/'):
        return filepath
    
    # Pattern 7: Nix store paths
    # /nix/store/xxx-go-1.21/share/go/src/...
    nix_match = re.match(r'^nix/store/[^/]+-go[^/]*/share/go/src/(.+)$', filepath, re.IGNORECASE)
    if nix_match:
        return nix_match.group(1)
    
    # Pattern 8: Generic - try to find stdlib package at any depth
    # Look for stdlib top-level package in the path
    parts = filepath.split('/')
    for i, part in enumerate(parts):
        if part in STDLIB_TOP_LEVEL:
            # Check if this looks like the start of the real path
            remaining = '/'.join(parts[i:])
            # Validate it ends with .go or contains typical file structure
            if remaining.endswith('.go') or '/' in remaining:
                return remaining
    
    return filepath


def _is_valid_domain(segment: str) -> bool:
    """
    Check if a path segment looks like a valid domain name.
    
    Args:
        segment: First segment of a path
        
    Returns:
        True if it looks like a domain (e.g., github.com, example.io)
    """
    if not segment or len(segment) < 4:  # Minimum: a.io
        return False
    
    # Must contain a dot
    if '.' not in segment:
        return False
    
    # Split into parts
    parts = segment.split('.')
    if len(parts) < 2:
        return False
    
    # TLD check
    tld = parts[-1].lower()
    if tld not in GO_MODULE_TLDS:
        return False
    
    # Domain name validation (alphanumeric and hyphens)
    for part in parts:
        if not part:
            return False
        if not re.match(r'^[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?$', part):
            return False
    
    return True


def _check_internal_package(filepath: str, package: str) -> Optional[str]:
    """
    Check if a filepath belongs to an internal package.
    
    Args:
        filepath: Normalized file path
        package: Package path (directory)
        
    Returns:
        Category string or None
    """
    # Check runtime internal first (more specific)
    for prefix in RUNTIME_INTERNAL_PREFIXES:
        if filepath.startswith(prefix + '/') or package == prefix:
            return FileCategory.RUNTIME_INTERNAL.value
    
    # Check stdlib internal
    for prefix in STDLIB_INTERNAL_PREFIXES:
        if filepath.startswith(prefix + '/') or package == prefix:
            return FileCategory.STDLIB_INTERNAL.value
    
    # Generic internal/ - default to stdlib internal
    if filepath.startswith('internal/'):
        return FileCategory.STDLIB_INTERNAL.value
    
    return None


def classify_go_filepath(filepath: str) -> Dict:
    """
    Classify a Go source file path into categories.
    """
    # Handle special cases
    if not filepath or filepath == "<unknown>":
        return {'category': FileCategory.UNKNOWN.value, 'package': '', 'is_test': False}
    
    if filepath == "<autogenerated>":
        return {'category': FileCategory.AUTOGENERATED.value, 'package': '', 'is_test': False}
    
    # Normalize path
    filepath = filepath.replace('\\', '/').strip()
   
    # Remove leading slash if present
    if filepath.startswith('/'):
        filepath = filepath[1:]
    
    # ===================== NORMALIZATION BLOCK =====================
    # Strip absolute Go SDK paths: /home/user/go/src/... -> ...
    match = re.search(r'/go(?:\d+\.\d+(?:\.\d+)?)?/src/(.+)$', filepath)
    if match:
        filepath = match.group(1)
    else:
        # Try without leading slash (already stripped above)
        match = re.search(r'go(?:\d+\.\d+(?:\.\d+)?)?/src/(.+)$', filepath)
        if match:
            filepath = match.group(1)
    
    # Handle _gomod_ prefix
    if filepath.startswith('_gomod_/'):
        filepath = filepath[8:]
    # ===================== END NORMALIZATION =====================
    
    # Check if test file
    is_test = '_test.go' in filepath
    
    # === Extract package path ===
    if '/' in filepath:
        package = filepath.rsplit('/', 1)[0]
    else:
        package = ''
    
    # === Get first segment for classification ===
    first_segment = filepath.split('/')[0] if '/' in filepath else filepath
    
    # === 1. CGO and special compiler-generated ===
    if first_segment.startswith('_cgo_') or '/_cgo_' in filepath:
        return {'category': FileCategory.CGO.value, 'package': package, 'is_test': is_test}
    
    # Check for cgo-generated files
    if any(x in filepath for x in ['_cgo_gotypes.go', '_cgo_import.go', 'cgo_linux.go']):
        return {'category': FileCategory.CGO.value, 'package': package, 'is_test': is_test}
    
    # === 2. Autogenerated ===
    if first_segment == '<autogenerated>' or filepath == '<autogenerated>':
        return {'category': FileCategory.AUTOGENERATED.value, 'package': package, 'is_test': is_test}
    
    # === 3. Runtime Core ===
    if first_segment == 'runtime':
        if filepath.startswith('runtime/internal/'):
            return {'category': FileCategory.RUNTIME_INTERNAL.value, 'package': package, 'is_test': is_test}
        else:
            return {'category': FileCategory.RUNTIME_CORE.value, 'package': package, 'is_test': is_test}
    
    # === 4. Internal Packages ===
    internal_category = _check_internal_package(filepath, package)
    if internal_category:
        return {'category': internal_category, 'package': package, 'is_test': is_test}
    
    # === 5. Vendor directory (third-party) ===
    if filepath.startswith('vendor/') or '/vendor/' in filepath:
        return {'category': FileCategory.THIRD_PARTY.value, 'package': package, 'is_test': is_test}
    
    # === 6. Known third-party domains ===
    if first_segment in KNOWN_THIRD_PARTY_DOMAINS:
        return {'category': FileCategory.THIRD_PARTY.value, 'package': package, 'is_test': is_test}
    
    # === 7. Domain-like pattern (third-party) ===
    if _is_valid_domain(first_segment):
        return {'category': FileCategory.THIRD_PARTY.value, 'package': package, 'is_test': is_test}
    
    # === 8. Standard Library (top-level match) ===
    if first_segment in STDLIB_TOP_LEVEL:
        return {'category': FileCategory.STDLIB_PUBLIC.value, 'package': package, 'is_test': is_test}
    
    # === 9. Command-line-arguments (main package) ===
    if first_segment == 'command-line-arguments':
        return {'category': FileCategory.APPLICATION.value, 'package': 'main', 'is_test': is_test}
    
    # === 10. Main package heuristics ===
    if filepath == 'main.go' or filepath.startswith('main/'):
        return {'category': FileCategory.APPLICATION.value, 'package': 'main', 'is_test': is_test}
    
    # === 11. Application code heuristics ===
    special_prefixes = {'_', '.', 'testdata'}
    
    if (
        '.' not in first_segment and
        first_segment not in STDLIB_TOP_LEVEL and
        first_segment not in special_prefixes and
        not first_segment.startswith('_')
    ):
        return {'category': FileCategory.APPLICATION.value, 'package': package, 'is_test': is_test}
    
    # === 12. Fallback: Check if path looks like it could be stdlib ===
    for part in filepath.split('/'):
        if part in STDLIB_TOP_LEVEL:
            return {'category': FileCategory.STDLIB_PUBLIC.value, 'package': package, 'is_test': is_test}
    
    # === Default: Unknown ===
    return {'category': FileCategory.UNKNOWN.value, 'package': package, 'is_test': is_test}

# =========================================================================
# Function-Name Classifier  (fallback when filepath is <unknown>)
# =========================================================================

def _extract_package_path(func_name: str) -> str:
    """
    Extract the Go import path from a fully-qualified function name.

    Examples:
        "main.main"                                  → "main"
        "fmt.Sprintf"                                → "fmt"
        "net/http.(*Server).ListenAndServe"          → "net/http"
        "github.com/gorilla/mux.(*Router).ServeHTTP" → "github.com/gorilla/mux"
        "wssoft/libs/fs.dirList.func1"               → "wssoft/libs/fs"
        "type..eq.main.Config"                       → inner recursion → "main"
        "runtime/internal/atomic.(*Int64).Load"      → "runtime/internal/atomic"
    """
    if not func_name:
        return None

    # ---- autogenerated wrappers: recurse on inner type path ----
    if func_name.startswith("type.."):
        rest = func_name.split(".", 3)   # ['type', '', 'eq', 'main.Config']
        if len(rest) >= 4:
            return _extract_package_path(rest[3])
        return None

    # ---- strip linker "go:" prefix (rare in pclntab) ----
    if func_name.startswith("go:"):
        func_name = func_name[3:]

    # ---- single-segment name (no slashes) ----
    slash_parts = func_name.split("/")
    if len(slash_parts) == 1:
        dot = func_name.find(".")
        if dot == -1:
            return func_name
        return func_name[:dot] or None

    # ---- multi-segment: prefix/lastSeg.Identifier ----
    prefix = "/".join(slash_parts[:-1])
    last_seg = slash_parts[-1]

    dot_pos = 0
    while True:
        dot_pos = last_seg.find(".", dot_pos)
        if dot_pos == -1:
            return f"{prefix}/{last_seg}"
        next_idx = dot_pos + 1
        if next_idx >= len(last_seg):
            return f"{prefix}/{last_seg[:dot_pos]}"
        nc = last_seg[next_idx]
        if nc.isupper() or nc == '(' or nc == '*':
            return f"{prefix}/{last_seg[:dot_pos]}"
        rest_after = last_seg[next_idx:]
        if '/' in rest_after or '.' in rest_after:
            dot_pos += 1
            continue
        return f"{prefix}/{last_seg[:dot_pos]}"


def _classify_package_path(pkg: str) -> str:
    """
    Classify a bare Go import path (no filename, no identifier).
    Returns a FileCategory value string.
    """
    if not pkg:
        return FileCategory.UNKNOWN.value

    parts = pkg.split("/")
    first = parts[0]

    # runtime core / internal
    if first == "runtime":
        if pkg.startswith("runtime/internal"):
            return FileCategory.RUNTIME_INTERNAL.value
        return FileCategory.RUNTIME_CORE.value

    # internal/*
    if first == "internal":
        for prefix in RUNTIME_INTERNAL_PREFIXES:
            if pkg == prefix or pkg.startswith(prefix + "/"):
                return FileCategory.RUNTIME_INTERNAL.value
        for prefix in STDLIB_INTERNAL_PREFIXES:
            if pkg == prefix or pkg.startswith(prefix + "/"):
                return FileCategory.STDLIB_INTERNAL.value
        return FileCategory.STDLIB_INTERNAL.value

    # crypto/internal, net/internal, vendor/golang.org, etc.
    for prefix in STDLIB_INTERNAL_PREFIXES:
        if pkg == prefix or pkg.startswith(prefix + "/"):
            return FileCategory.STDLIB_INTERNAL.value

    if first == "vendor":
        return FileCategory.THIRD_PARTY.value

    if first in KNOWN_THIRD_PARTY_DOMAINS:
        return FileCategory.THIRD_PARTY.value

    if _is_valid_domain(first):
        return FileCategory.THIRD_PARTY.value

    if first in STDLIB_TOP_LEVEL:
        return FileCategory.STDLIB_PUBLIC.value

    if first in ("main", "command-line-arguments"):
        return FileCategory.APPLICATION.value

    # No dot in first segment → not a domain → application code
    if "." not in first and first not in STDLIB_TOP_LEVEL:
        return FileCategory.APPLICATION.value

    return FileCategory.UNKNOWN.value


def classify_go_func_name(func_name: str) -> dict:
    """
    Classify a Go function by its fully-qualified symbol name.

    Use as a fallback when classify_go_filepath() returns "unknown"
    (source filepath missing from pclntab).

    Returns same dict shape: {'category': str, 'package': str, 'is_test': bool}
    """
    if not func_name or func_name.startswith("<"):
        return {"category": FileCategory.UNKNOWN.value, "package": "", "is_test": False}

    # ---- autogenerated: type..eq.X / type..hash.X ----
    if func_name.startswith("type.."):
        pkg = _extract_package_path(func_name)
        if pkg:
            inner = _classify_package_path(pkg)
            if inner != FileCategory.UNKNOWN.value:
                return {"category": FileCategory.AUTOGENERATED.value,
                        "package": pkg, "is_test": False}
        return {"category": FileCategory.AUTOGENERATED.value,
                "package": "", "is_test": False}

    # ---- go.* — distinguish go.uber.org (third-party) from go.buildid (autogenerated) ----
    if func_name.startswith("go."):
        first_seg = func_name.split("/")[0]
        if not (_is_valid_domain(first_seg) or first_seg in KNOWN_THIRD_PARTY_DOMAINS):
            return {"category": FileCategory.AUTOGENERATED.value,
                    "package": "", "is_test": False}

    # ---- normal classification ----
    pkg = _extract_package_path(func_name)
    if not pkg:
        return {"category": FileCategory.UNKNOWN.value, "package": "", "is_test": False}

    category = _classify_package_path(pkg)
    is_test = "_test" in func_name

    return {"category": category, "package": pkg, "is_test": is_test}

def classify_files_batch(filepaths: list) -> Dict[str, Dict]:
    """
    Classify multiple file paths efficiently.
    
    Args:
        filepaths: List of file paths
        
    Returns:
        Dict mapping filepath -> classification
    """
    cache = {}
    for fp in filepaths:
        if fp not in cache:
            cache[fp] = classify_go_filepath(fp)
    return cache


def get_classification_stats(classifications: Dict[str, Dict]) -> Dict[str, int]:
    """
    Get count of each category.
    
    Args:
        classifications: Dict from classify_files_batch
        
    Returns:
        Dict mapping category name -> count
    """
    stats = {}
    for fp, cls in classifications.items():
        cat = cls['category']
        stats[cat] = stats.get(cat, 0) + 1
    return stats


def get_category_files(classifications: Dict[str, Dict], category: FileCategory) -> list:
    """
    Get all files belonging to a specific category.
    
    Args:
        classifications: Dict from classify_files_batch
        category: FileCategory to filter by
        
    Returns:
        List of file paths in that category
    """
    return [
        fp for fp, cls in classifications.items()
        if cls['category'] == category.value
    ]



